#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = configPkg
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
C:/ti/xdctools_3_50_05_12_core/packages/xdc/utils.js:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/utils.js
C:/ti/xdctools_3_50_05_12_core/packages/xdc/xdc.tci:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/xdc.tci
C:/ti/xdctools_3_50_05_12_core/packages/xdc/template.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/template.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/om2.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/om2.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/xmlgen.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/xmlgen.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/xmlgen2.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/xmlgen2.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/Warnings.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/Warnings.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/IPackage.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/IPackage.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/package.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/package.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/services/global/Clock.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/services/global/Clock.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/services/global/Trace.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/services/global/Trace.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/bld.js:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/bld.js
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/BuildEnvironment.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/PackageContents.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/PackageContents.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/_gen.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/_gen.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Library.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Library.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Executable.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Executable.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Repository.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Repository.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Configuration.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Configuration.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Script.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Script.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Manifest.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Manifest.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Utils.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/Utils.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/ITarget.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/ITarget.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/ITarget2.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/ITarget2.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/ITarget3.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/ITarget3.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/ITargetFilter.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/package.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/bld/package.xs
package.mak: config.bld
C:/ti/simplelink_cc32xx_sdk_2_10_00_04/kernel/tirtos/packages/iar/targets/arm/ITarget.xs:
package.mak: C:/ti/simplelink_cc32xx_sdk_2_10_00_04/kernel/tirtos/packages/iar/targets/arm/ITarget.xs
C:/ti/simplelink_cc32xx_sdk_2_10_00_04/kernel/tirtos/packages/iar/targets/arm/package.xs:
package.mak: C:/ti/simplelink_cc32xx_sdk_2_10_00_04/kernel/tirtos/packages/iar/targets/arm/package.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/services/io/File.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/services/io/File.xs
C:/ti/xdctools_3_50_05_12_core/packages/xdc/services/io/package.xs:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/services/io/package.xs
package.mak: package.bld
C:/ti/xdctools_3_50_05_12_core/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/tools/configuro/template/compiler.opt.xdt
C:/ti/xdctools_3_50_05_12_core/packages/xdc/tools/configuro/template/compiler.defs.xdt:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/tools/configuro/template/compiler.defs.xdt
C:/ti/xdctools_3_50_05_12_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
C:/ti/xdctools_3_50_05_12_core/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: C:/ti/xdctools_3_50_05_12_core/packages/xdc/tools/configuro/template/package.xs.xdt
endif

iar.targets.arm.M4.rootDir ?= C:/PROGRA~2/IARSYS~1/EMBEDD~1.0/arm
iar.targets.arm.packageBase ?= C:/ti/simplelink_cc32xx_sdk_2_10_00_04/kernel/tirtos/packages/iar/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.orm4
.PHONY: all,rm4 .dlls,rm4 .executables,rm4 test,rm4
all,rm4: .executables,rm4
.executables,rm4: .libraries,rm4
.executables,rm4: .dlls,rm4
.dlls,rm4: .libraries,rm4
.libraries,rm4: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,rm4
	@$(ECHO) xdc .executables,rm4
	@$(ECHO) xdc .libraries,rm4
	@$(ECHO) xdc .dlls,rm4


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_configPkg.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package configPkg" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,rm4 .dlls: Cornell.prm4

-include package/cfg/Cornell_prm4.mak
-include package/cfg/Cornell_prm4.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/Cornell_prm4.dep
endif
Cornell.prm4: package/cfg/Cornell_prm4.xdl
	@


ifeq (,$(wildcard .libraries,rm4))
Cornell.prm4 package/cfg/Cornell_prm4.c: .libraries,rm4
endif

package/cfg/Cornell_prm4.c package/cfg/Cornell_prm4.h package/cfg/Cornell_prm4.xdl: override _PROG_NAME := Cornell.xrm4
package/cfg/Cornell_prm4.c: package/cfg/Cornell_prm4.cfg
package/cfg/Cornell_prm4.xdc.inc: package/cfg/Cornell_prm4.xdl
package/cfg/Cornell_prm4.xdl package/cfg/Cornell_prm4.c: .interfaces

clean:: clean,rm4
	-$(RM) package/cfg/Cornell_prm4.cfg
	-$(RM) package/cfg/Cornell_prm4.dep
	-$(RM) package/cfg/Cornell_prm4.c
	-$(RM) package/cfg/Cornell_prm4.xdc.inc

clean,rm4::
	-$(RM) Cornell.prm4
.executables,rm4 .executables: Cornell.xrm4

Cornell.xrm4: |Cornell.prm4

-include package/cfg/Cornell.xrm4.mak
Cornell.xrm4: package/cfg/Cornell_prm4.orm4 
	$(RM) $@
	@$(MSG) lnkrm4 $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	LC_ALL=C $(iar.targets.arm.M4.rootDir)/bin/ilinkarm --redirect _Printf=_PrintfFullNoMb --redirect _Scanf=_ScanfFullNoMb -o D:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src/Debug/Exe/Cornell.out --map D:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src/Debug/List/Cornell.map --config D:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src/Cornell_CC3220SF_LAUNCHXL_TIRTOS.icf -f D:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src/configPkg/linker.cmd c:/ti/simplelink_cc32xx_sdk_2_10_00_04/source/ti/display/lib/display.arm4 c:/ti/simplelink_cc32xx_sdk_2_10_00_04/source/ti/grlib/lib/iar/m4/grlib.a c:/ti/simplelink_cc32xx_sdk_2_10_00_04/source/third_party/spiffs/lib/iar/m4/spiffs.a c:/ti/simplelink_cc32xx_sdk_2_10_00_04/source/ti/drivers/lib/drivers_cc32xx.arm4 c:/ti/simplelink_cc32xx_sdk_2_10_00_04/source/third_party/fatfs/lib/iar/m4/fatfs.a c:/ti/simplelink_cc32xx_sdk_2_10_00_04/kernel/tirtos/packages/ti/dpl/lib/dpl_cc32xx.arm4 c:/ti/simplelink_cc32xx_sdk_2_10_00_04/source/ti/devices/cc32xx/driverlib/iar/Release/driverlib.a c:/ti/simplelink_cc32xx_sdk_2_10_00_04/source/ti/drivers/net/wifi/iar/rtos/simplelink.a c:/ti/simplelink_cc32xx_sdk_2_10_00_04/source/ti/net/http/lib/iar/m4/httpclient_debug.a --silent --cpu=Cortex-M4 --redirect _Printf=_PrintfSmall --redirect _Scanf=_ScanfSmall --semihosting --entry __iar_program_start --redirect __iar_sh_stdout=__iar_sh_stdout_swo --vfe --utf8_text_in --text_out utf8 --silent -o $@ package/cfg/Cornell_prm4.orm4 -f package/cfg/Cornell_prm4.xdl  --semihosting=iar_breakpoint  --cpu=Cortex-M4 --map $(XDCCFGDIR)/$@.map  --redirect _Printf=_PrintfSmall --redirect _Scanf=_ScanfSmall 
	

Cornell.test test,rm4 test: Cornell.xrm4.test

Cornell.xrm4.test:: Cornell.xrm4
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 Cornell.xrm4.test
else
	@$(MSG) running $<  ...
	$(call EXEC.Cornell.xrm4, ) 
endif

clean,rm4::
	-$(RM) $(wildcard .tmp,Cornell.xrm4,*)


clean:: clean,rm4

clean,rm4::
	-$(RM) Cornell.xrm4
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
Cornell_prm4.orm4,copy : package/cfg/Cornell_prm4.orm4
Cornell_prm4.srm4,copy : package/cfg/Cornell_prm4.srm4

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,configPkg
ifeq (,$(MK_NOGENDEPS))
-include package/rel/configPkg.tar.dep
endif
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.bld.xml
package/rel/configPkg/configPkg/package/package.rel.xml: package/build.cfg
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.xdc.inc
package/rel/configPkg/configPkg/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

configPkg.tar: package/rel/configPkg.xdc.inc package/rel/configPkg/configPkg/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/configPkg.xdc.inc,package/rel/configPkg.tar.dep)


release release,configPkg: all configPkg.tar
clean:: .clean
	-$(RM) configPkg.tar
	-$(RM) package/rel/configPkg.xdc.inc
	-$(RM) package/rel/configPkg.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
