#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = iar.targets.arm.M4{1,0,8.22,1
#
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/Cornell_prm4.orm4.dep
package/cfg/Cornell_prm4.orm4.dep: ;
endif

package/cfg/Cornell_prm4.orm4: | .interfaces
package/cfg/Cornell_prm4.orm4: package/cfg/Cornell_prm4.c package/cfg/Cornell_prm4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clrm4 $< ...
	LC_ALL=C $(iar.targets.arm.M4.rootDir)/bin/iccarm    -D TI_DRIVERS_UART_DMA   -D SL_PLATFORM_MULTI_THREADED   -D NDEBUG   -D ENABLE_LPDS   -ID:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src   -Ic:/ti/simplelink_cc32xx_sdk_2_10_00_04/source   -Ic:/ti/simplelink_cc32xx_sdk_2_10_00_04/source/ti/posix/iar   -Ic:/ti/simplelink_cc32xx_sdk_2_10_00_04/source/ti/net/http   -I D:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src/System/HeaderFiles/   -I D:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src/JSONParser/include/   -I D:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src/HttpParser/include/   -I D:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src/   --silent --aeabi --cpu=Cortex-M4 --diag_suppress=Pa050,Go005 --endian=little -e --thumb   -Dxdc_cfg__xheader__='"configPkg/package/cfg/Cornell_prm4.h"'  -Dxdc_target_name__=M4 -Dxdc_target_types__=iar/targets/arm/std.h -Dxdc_bld__profile_release_full -Dxdc_bld__vers_1_0_8_22_1 -Ohs --dlib_config $(iar.targets.arm.M4.rootDir)/inc/c/DLib_Config_Full.h  $(XDCINCS)  -o $@  $<
	
	-@$(FIXDEP) $@.dep $@.dep
	

package/cfg/Cornell_prm4.srm4: | .interfaces
package/cfg/Cornell_prm4.srm4: package/cfg/Cornell_prm4.c package/cfg/Cornell_prm4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clrm4 $< ...
	LC_ALL=C $(iar.targets.arm.M4.rootDir)/bin/iccarm    -D TI_DRIVERS_UART_DMA   -D SL_PLATFORM_MULTI_THREADED   -D NDEBUG   -D ENABLE_LPDS   -ID:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src   -Ic:/ti/simplelink_cc32xx_sdk_2_10_00_04/source   -Ic:/ti/simplelink_cc32xx_sdk_2_10_00_04/source/ti/posix/iar   -Ic:/ti/simplelink_cc32xx_sdk_2_10_00_04/source/ti/net/http   -I D:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src/System/HeaderFiles/   -I D:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src/JSONParser/include/   -I D:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src/HttpParser/include/   -I D:/ISC/Cornell/Cornell_FW/Cornell_V1/Build19/Build19/src/   --silent --aeabi --cpu=Cortex-M4 --diag_suppress=Pa050,Go005 --endian=little -e --thumb   -Dxdc_cfg__xheader__='"configPkg/package/cfg/Cornell_prm4.h"'  -Dxdc_target_name__=M4 -Dxdc_target_types__=iar/targets/arm/std.h -Dxdc_bld__profile_release_full -Dxdc_bld__vers_1_0_8_22_1 -Ohs --dlib_config $(iar.targets.arm.M4.rootDir)/inc/c/DLib_Config_Full.h  $(XDCINCS)  -o $@  $<
	
	-@$(FIXDEP) $@.dep $@.dep
	

clean,rm4 ::
	-$(RM) package/cfg/Cornell_prm4.orm4
	-$(RM) package/cfg/Cornell_prm4.srm4

Cornell.prm4: package/cfg/Cornell_prm4.orm4 package/cfg/Cornell_prm4.mak

clean::
	-$(RM) package/cfg/Cornell_prm4.mak
