#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = iar.targets.arm.M4{1,0,8.22,1
#
Cornell.xrm4: package/cfg/Cornell.xrm4.mak

clean::
	-$(RM) package/cfg/Cornell.xrm4.mak
